# Integrating Elasticsearch and Kibana into Docker-Compose
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: shopdev_es
    environment:
      - node.name=shopdev_es
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node

      ## Basic Auth
      # - xpack.security.enabled=true
      ## default username is: elastic
      # - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: shopdev_kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
# run: docker-compose up -d
# stop: docker-compose down

